---

# fail when distribution is not supported

- name: check if distribution is supported
  fail: msg="'{{ ansible_distribution }}' is not supported by this role"
  when: ansible_distribution not in ["Gentoo"]


# initialize portage

- import_tasks: portage.yml


# set system timezone

- import_tasks: timezone.yml


# set hostname

- import_tasks: hostname.yml


# write hosts entries

- import_tasks: hosts.yml


# set locale

- import_tasks: locale.yml


# post tasks

- meta: flush_handlers
