---

# fail when distribution is not supported

- name: check if distribution is supported
  fail: msg="'{{ ansible_distribution }}' is not supported by this role"
  when: ansible_distribution not in ["Gentoo"]


# run os specific tasks

- import_tasks: gentoo/main.yml
  when: ansible_distribution == "Gentoo"


# set hostname

- import_tasks: set-hostname.yml


# write hosts entries

- import_tasks: write-host-entries.yml


# set locale

- import_tasks: locale.yaml
