---

# check if equery is present. if not so execute required tasks

- name: check if equery is present
  become: yes
  command: equery --version
  register: check_equery
  ignore_errors: yes
  changed_when: false


# update package tree

- name: update package tree
  become: yes
  raw: emerge --sync
  when: check_equery.rc != 0


# write makeopts

- name: write makeopts flags
  become: yes
  lineinfile:
    path: /etc/portage/make.conf
    regexp: "^MAKEOPTS="
    line: "MAKEOPTS={{ system_makeopts }}"

# install gentoolkit package required for ansible portage module

- name: install gentoolkit
  become: yes
  raw: emerge app-portage/gentoolkit
  when: check_equery.rc != 0


# update system package tree

- name: update package tree
  become: yes
  portage: sync="web"
  when: system_update
