---

# set system timezone

- name: check for localtime file
  stat: path=/etc/localtime
  register: localtime_file

- name: remove localtime file if not symlink
  become: yes
  file: path=/etc/localtime state=absent
  when: localtime_file.stat.exists and not localtime_file.stat.islnk

- name: set system localtime
  become: yes
  file:
    src: /usr/share/zoneinfo/{{ system_timezone }}
    dest: /etc/localtime
    state: link
  notify: system - timezone
